### ISSUE TITLE
Calculate a percentage

### ISSUE THREAD

**Issue by ngocsangyem** [generalui/jekyll-image-size#6]
Hi,
Can we calculate a percentage between width and height of the image?

**Comment by felixboet** [comment]
@ngocsangyem Maybe a little late, but I think you can use {% imagesize image:height?width=100.0 %}

**Comment by ngocsangyem** [comment]
Hi @felixboet , thank you for your solution.  I want to calculate the percentage in the liquid template but I think this plugin not supported yet. I will close this issue.
